[build]
  publish = "public"
  command = "hugo --gc --minify -b /"

[context.deploy-preview]
  command = "hugo --gc --minify -b /"

[context.branch-deploy]
  command = "hugo --gc --minify -b /"

[build.environment]
  HUGO_VERSION = "0.161.1"
